/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskResponse {
  createdDate?: string;
  description?: string;
  dueDate?: string;
  id?: number;
  isDone?: boolean;
  lastUpdatedDate?: string;
  title?: string;
}
