spring:
  datasource:
    url: jdbc:postgresql://localhost5432/todo_db
    username: sif
    password: password
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/todo-realm"
server:
  port: 8090